### PR TITLE
Add support for throwing exceptions on get(), update() and delete()

### PR DESCRIPTION
**Pull request by mrunix00**

### CODE REVIEW

**Comment by atn832** [comment]
However, it does not work for Queries:
```dart
      final movies = firestore.collection('movies');
      final query = firestore
          .collection('movies')
          .where('title', isEqualTo: 'Test Movie');

      await movies.add({
        'title': 'Test Movie',
      });

      whenCalling(Invocation.method(#get, null))
          .on(query)
          .thenThrow(FirebaseException(plugin: 'firestore'));

      // this throws the exception correctly.
      whenCalling(Invocation.method(#get, null))
          .on(query)
          .thenThrow(FirebaseException(plugin: 'firestore'));

      // but this does not throw the exception.
      expect(
        () async => await firestore
            .collection('movies')
            .where('title', isEqualTo: 'Test Movie')
            .get(GetOptions(source: Source.server)),
        throwsA(isA<FirebaseException>()),
      );
```

**Comment by atn832** [comment]
Just uploaded your PR to version 2.4.3. Thanks again! https://pub.dev/packages/fake_cloud_firestore/changelog#243

**Comment by mrunix00** [comment]
> However, it does not work for Queries:
> 
> ```dart
>       final movies = firestore.collection('movies');
>       final query = firestore
>           .collection('movies')
>           .where('title', isEqualTo: 'Test Movie');
> 
>       await movies.add({
>         'title': 'Test Movie',
>       });
> 
>       whenCalling(Invocation.method(#get, null))
>           .on(query)
>           .thenThrow(FirebaseException(plugin: 'firestore'));
> 
>       // this throws the exception correctly.
>       whenCalling(Invocation.method(#get, null))
>           .on(query)
>           .thenThrow(FirebaseException(plugin: 'firestore'));
> 
>       // but this does not throw the exception.
>       expect(
>         () async => await firestore
>             .collection('movies')
>             .where('title', isEqualTo: 'Test Movie')
>             .get(GetOptions(source: Source.server)),
>         throwsA(isA<FirebaseException>()),
>       );
> ```

Yeah I just noticed that lately, I'll try to find a good fix for that

**Comment by atn832** [comment]
I debugged a bit earlier, and it seemed that when we call `where`, it creates an operator function, and this function has a different hash every time even if it has the same code. Perhaps if we set up the operator function to return consistent hashes (I don't know how yet), it will work.

**Pull request merged**
